const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;
const BLOB_READ_WRITE_TOKEN = process.env.BLOB_READ_WRITE_TOKEN;
const SECRET_KEY = process.env.SECRET_KEY;

export {
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  BLOB_READ_WRITE_TOKEN,
  SECRET_KEY,
};
